== OSGi Bundles for Akka

image:https://badges.gitter.im/woq-blended/akka-osgi.svg[link="https://gitter.im/woq-blended/akka-osgi?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

With https://github.com/akka/akka/issues/28304[Issue 28304] the akka team has announced that the OSGi support for
Akka shall be moved out of the main project as per Akka 2.6.2.

As of today, https://akka.io/[Akka 2.6.6] is still released with OSGi Headers in most of it's bundles, but the goal
of removing the OSGi support is still https://github.com/akka/akka/issues/28304#issuecomment-620022900[valid].

This project aims to provide jars based on the original jars provided by Akka with proper Manifests so that Akka
can be used within OSGi. Our own https://github.com/woq-blended/blended[project] heavily relies on Akka, Akka Stream
and Akka Http, so that we need those bundles for ourselves.

=== Approach

We will consume the jars for a given Akka version and run them through our build process to provide the OSGi manifest.
For each jar we run a quick sanity check to make sure that our bundling process didn't lose any content of the
original jar.

We start out the process with a limited set of Akka jars required by our own project. Over time we may add more
bundles, perhaps with some help from the community.

Later in the process we hope to add more tests to verify that the bundles are working as expected. For now we are
using the test we have in our main project to validate that our bundles are working.

=== Revision and Republishing 

This project will increase it's own version with every release. This version will be appended to the version number 
of the original version of the akka jar. For example, if our version is `0.1` and the akka version is `2.6.6`, then 
the published version of the OSGi enabled jar will be `2.6.6-0.1`.

We will publish our releases in http://search.maven.org/#search|ga|1|g%3A%22de.wayofquality.blended%22[Maven Central].

=== Rewrite published pom files

Within our published pom files we will include all compile dependencies from the original akka jar. If the dependency 
points to a jar that is also handled by this project, the dependency will be rewritten to point to the OSGi enabled 
jar with the same revision instead. 

NOTE: This is done to make the OSGi manifest entries visible to the bnd tool, so that proper imports can be generated 
for any bundles built on top of the OSGi enabled akka jars. Even if Akka still provides OSGi manifest headers themselves, 
you might want to reference the jar from this project in your build to ensure future compatibility. 

=== Build from source

We use https://github.com/lihaoyi/mill[Mill build tool] to build the bundles.

After cloning the repository, simply navigate to the checkout directory and use the bundled mill
script `./millw`, which is a copy of https://github.com/lefou/millw[lefou/millw].

=== Selected build targets / commands

|===
| mill command | Description

| `mill __.publishLocal`
| Build and publish all publishable artifacts into a local ivy2 repository.

| `mill __.publishM2Local`
| Build and publish all publishable artifacts into a local Maven2 repository.

| `mill -j 0 -k wrapped[2.13.2].__.testCached`
| Run all unit test in parallel for Scala version 2.13.2 and keep mill going even a test failure occured
|===

=== IDE support

We use https://www.jetbrains.com/idea/[IntelliJ] in our project.
You can generate IntelliJ IDEA project files with mill with the following commandline:

----
mill mill.scalalib.GenIdea/idea
----

== Download  artifacts from Maven Central

At the moment we not released any bundles. Once we have a stable set of bundles that can be used,
they will be available via http://search.maven.org/#search|ga|1|g%3A%22de.wayofquality.blended%22[Maven Central].

== License

The Blended Akka Bundles are published under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]

== Contribute

All contributions to the project are more than welcome. Please be nice and follow the https://www.scala-lang.org/conduct[Scala Code of Conduct]. 

For any CoC-related questions within this project, please send an eMail to andreas@wayofquality.de 

=== Improve the documentation 

If you want to improve the documentation, feel free to create a PR. We are looking for projects using our bundles, 
links to working OSGi setups etc.

=== Request more jars to be supported 

We are starting with the jars that we require in our https://github.com/woq-blended/blended[project]. If you are missing 
jars you would like to use, please open an https://github.com/woq-blended/blended/issues/new/choose[issue] and consider 
creating a PR afterwards.

=== Report an issue with a bundle provided by this project 

If you are using one of our bundles and run into an OSGi problem, please open an https://github.com/woq-blended/akka-osgi/issues/new?assignees=&labels=&template=osgi-runtime-problem.md&title=[issue].

NOTE: Please do not report akka related issues in our project. These should be reported to the https://github.com/akka/akka[akka project]. 

== Projects using akka-osgi

The following projects are using akka-osgi provided bundles:

- https://github.com/woq-blended/blended[Blended]
- https://github.com/woq-blended/blended.container[Blended Demo Container]

== Supporters

https://www.jetbrains.com[JetBrains] is kindly supporting our project with full developer licenses
of their product stack.




